# Generated by Django 4.0.5 on 2022-07-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='characteristic_id',
            new_name='characteristic',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='group_id',
            new_name='group',
        ),
    ]
